name: Build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ENABLE_QEMU: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: now
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Checkout
        uses: actions/checkout@v4

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        if: ${{ env.ENABLE_QEMU == '1' }}
        uses: docker/setup-qemu-action@v3

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # See issue with multi-arch build + load : https://github.com/docker/buildx/issues/59
      - name: Build images (multi-architecture)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/386
            linux/arm64/v8
          push: false
          load: false
          tags: ghusta/postgres-world-db:ci_${{ steps.now.outputs.timestamp }}

      - name: Build image for latest postgres
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            POSTGRES_TAG=latest
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: false
          load: false
          tags: ghusta/postgres-world-db:ci_${{ steps.now.outputs.timestamp }}-latest

      - name: Build image for latest alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            POSTGRES_TAG=alpine
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: false
          load: false
          tags: ghusta/postgres-world-db:ci_${{ steps.now.outputs.timestamp }}-alpine

      # See : https://github.com/djimenezc/docker-multi-arch/commit/abf1ccfc0c37d4b9cbdce5a96b6fb5d48903e6a8
      - name: Load only one architecture
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: ghusta/postgres-world-db:ci_${{ steps.now.outputs.timestamp }}

      - name: List Docker images (arch linux/amd64)
        run: docker image ls ghusta/*